# Generated by Django 5.0.7 on 2024-07-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('cedula', models.IntegerField()),
                ('domicilio', models.CharField(max_length=200)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Coctail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('garnishes', models.CharField(max_length=100)),
                ('mixers', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paquetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePaquete', models.CharField(max_length=150)),
                ('numeroCocteles', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('insumos', models.CharField(max_length=200)),
                ('numeroPersonas', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
    ]
