# Generated by Django 5.0.7 on 2024-07-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bananas_coctails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coctail',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='coctails'),
        ),
    ]
