# Generated by Django 5.0.7 on 2024-07-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bananas_coctails', '0002_coctail_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
