# Generated by Django 5.0.7 on 2024-08-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bananas_coctails', '0004_clientes_password_clientes_user_alter_clientes_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='coctail',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
